/**
 * Writes public/sitemap.xml from static routes + resource slugs (single source of truth).
 * Run via: npm run generate:sitemap (also runs automatically before production build).
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { resources } from '../src/data/resources.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const outPath = join(root, 'public', 'sitemap.xml')
const edgePathsPath = join(root, 'generated', 'middleware-paths.js')

const BASE = 'https://zarmediagroup.com'
const today = new Date().toISOString().slice(0, 10)

const sitemapStaticPathList = [
  '/',
  '/what-we-do',
  '/about/team',
  '/services',
  '/services/website-as-a-service',
  '/services/workflow-integration',
  '/services/accounting-portals-crm',
  '/services/client-portal',
  '/services/compliance-trust',
  '/resources',
  '/contact',
  '/privacy-policy',
  '/terms-of-service',
  '/cookie-policy',
]

/** Includes paths the SPA handles but which must not appear in sitemap.xml */
const middlewareStaticPathList = [...sitemapStaticPathList, '/404']

const staticPaths = sitemapStaticPathList.map((path) => ({
  path,
  changefreq:
    path === '/'
      ? 'weekly'
      : path === '/services' || path.startsWith('/services')
        ? 'weekly'
        : path === '/resources'
          ? 'weekly'
          : path === '/contact'
            ? 'monthly'
            : path.startsWith('/privacy') || path.startsWith('/terms') || path.startsWith('/cookie')
              ? 'yearly'
              : 'monthly',
  priority:
    path === '/'
      ? '1.0'
      : path === '/services' || path.startsWith('/services') || path === '/what-we-do'
        ? '0.9'
        : path === '/resources' || path === '/contact'
          ? '0.8'
          : path === '/about/team'
            ? '0.7'
            : '0.3',
  lastmod: today,
}))

function urlEntry(loc, lastmod, changefreq, priority) {
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority}</priority>
  </url>`
}

const resourceEntries = resources.map((r) =>
  urlEntry(
    `${BASE}/resources/${r.slug}`,
    (r.dateISO || today).slice(0, 10),
    'monthly',
    '0.7',
  ),
)

const staticEntries = staticPaths.map((p) =>
  urlEntry(`${BASE}${p.path}`, p.lastmod, p.changefreq, p.priority),
)

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
          http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${staticEntries.join('\n')}
${resourceEntries.join('\n')}
</urlset>
`

writeFileSync(outPath, xml, 'utf8')
console.log(`Wrote ${outPath} (${staticPaths.length + resources.length} URLs)`)

// ── Vercel Edge Middleware: valid SPA paths + resource slugs ───────────────
mkdirSync(dirname(edgePathsPath), { recursive: true })
const slugList = resources.map((r) => r.slug)
const prerenderPaths = [
  ...middlewareStaticPathList.filter((p) => p !== '/404'),
  ...slugList.map((slug) => `/resources/${slug}`),
]
const edgeCode = `// AUTO-GENERATED by scripts/generate-sitemap.mjs — do not edit by hand.
export const STATIC_PATHS = ${JSON.stringify(middlewareStaticPathList)}
export const RESOURCE_SLUGS = ${JSON.stringify(slugList)}
export const PRERENDER_PATHS = ${JSON.stringify(prerenderPaths)}
`
writeFileSync(edgePathsPath, edgeCode, 'utf8')
console.log(`Wrote ${edgePathsPath} (${prerenderPaths.length} prerender paths)`)
